### ISSUE TITLE
Limited lunch review length

### ISSUE THREAD

**Issue by TC01** [bhaney/pennbot#11]
Today someone tried to leave a lunch review that was more than 250 characters and pennbot complained:

```
ERROR:  value too long for type character varying(250)
```

What database server is pennbot using as a backend for these things? I know postgres and mysql, at least, can support arbitrary variable length text (apparently using the [text](https://www.postgresql.org/docs/11/datatype-character.html) type?).

**Comment by bhaney** [comment]
https://github.com/bhaney/lunchdb is the database code, though the actual instance of the database is on my server. The functions that were used to create the tables in the first place are in `create_tables.py` so if you know the command to modify a column after a table has been created, let me know and I can run it.

**Comment by bhaney** [comment]
Also to answer your question, it's using postgresql

**Comment by TC01** [comment]
Oh, sorry for not getting back to you!

According to [StackOverflow](https://stackoverflow.com/questions/2813049/postgres-convert-varchar-to-text), you should be able to do this to convert to the "text" type, which is of arbitrary length:

```
ALTER TABLE table1 ALTER COLUMN column1 TYPE text;
```

**Comment by bhaney** [comment]
It's been updated- the comment column is now of type `text`
