### ISSUE TITLE
"Error: certificate has expired" when checking indico

### ISSUE THREAD

**Issue by TC01** [bhaney/pennbot#13]
Hi @bhaney,

pennbot has just started to complain that a certificate has expired when it tries to fetch indico events:

```
Encountered an error in pyindico: Error: certificate has expired
```

It seems to be echoing this into the Everyone channel every half hour (when it checks to see what the next meeting is).

Any idea what's going on here? My browser, at least, thinks the certs on both `https://bots.bijanhaney.com/` and `https://indico.cern.ch/` are okay.

**Comment by bhaney** [comment]
Hey Ben! 

Yeah, the certs seem to be fine -- I will need to check the logs for pennbot to see what is up. I wish I could at least restart/turn off pennbot until that time, but I am at work and won't be back to my home computer until something like 5:30pm ET -- I'll take care of it as soon as I get home.

**Comment by bhaney** [comment]
@TC01 I restarted the service, let me know if it is still causing problems.

**Comment by TC01** [comment]
Thanks for looking into it!

There was still an error posted at 6:30-- I'll let you know if another one gets posted at 7 on the next half hour increment.

**Comment by bhaney** [comment]
Looking at the pyindico logs when I try to visit https://bots.bijanhaney.com/indico/next/upenn

It gives this following error
```
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: return self.view_functions[rule.endpoint](**req.view_args)
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: File "/var/www/bots.bijanhaney.com/pyindico/app.py", line 12, in next_meeting
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: nm,date = nextmeet.main(category,getenv("CONFIG_PATH"))
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: File "/var/www/bots.bijanhaney.com/pyindico/pyindico/nextmeet.py", line 41, in main
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: cat_events = events.parse_category(contents, category)
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: File "/var/www/bots.bijanhaney.com/pyindico/pyindico/events.py", line 65, in parse_category
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: parent_path = parents[0]['path']
Sep 30 18:44:41 centos-1gb-nyc3-01 gunicorn[796]: IndexError: list index out of range
```

Did the API for indico change? If it is a problem in [pyindico](https://gitlab.cern.ch/brosser/pyindico) I can pull the updates and restart the indico bot

**Comment by bhaney** [comment]
Could also be that either the api or secret changed

**Comment by TC01** [comment]
Huh... weird.

I tried to run the script myself, and I reproduced a *different* crash, which I just fixed. I also added some guards around that line to abort if `parents` is not formatted as expected. Maybe try pulling and see if it fixes it?

It could be that the credentials have expired; pennbot's been announcing public meetings like thesis defenses but not group meetings. But I'm not sure why it would have suddenly started to crash, so maybe the API changed.

**Comment by bhaney** [comment]
Looks like it's fixed! (at least when I visit the endpoint) Thanks for the updates to the pyindico code. 

If you figure out why the list might not be populating, and you push a fix to pyindico, you can always open another issue here and I will pull the changes.

At least you will stop getting a message every 30 minutes now. If you could confirm that 9pm doesn't send an error, I will then close this issue.

**Comment by TC01** [comment]
Yes, it looks like pennbot has stopped posting error messages. Thanks for looking into this!
